version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stockscreener_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///./database/stockscreener.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=true
      - ENVIRONMENT=development
    depends_on:
      - db-init
    networks:
      - stockscreener_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stockscreener_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    depends_on:
      - backend
    networks:
      - stockscreener_network

  db-init:
    image: alpine:latest
    container_name: stockscreener_db_init
    volumes:
      - ./database:/database
    command: >
      sh -c "
        mkdir -p /database &&
        touch /database/stockscreener.db &&
        chmod 666 /database/stockscreener.db
      "
    networks:
      - stockscreener_network

volumes:
  database_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database

networks:
  stockscreener_network:
    driver: bridge